# Prod Secrets Manager key = "${local.name}/db/credentials" for environment=prod.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redemption-db
  namespace: redemption
spec:
  dataFrom:
    - extract:
        key: redemption-prod/db/credentials
