apiVersion: v1
kind: ServiceAccount
metadata:
  name: redemption-secretstore
  namespace: redemption
  annotations:
    # Replace with terraform output: app_secrets_irsa_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::801100257021:role/redemption-dev-external-secrets
