# Internet-facing ALB provisioned by the AWS Load Balancer Controller.
# TLS terminates at the ALB via an ACM certificate; WAF is associated at the ALB.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redemption-api
  namespace: redemption
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    # Replace with your ACM certificate ARN fro thixpin.me
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:801100257021:certificate/e1b6f044-bac8-435b-8826-d9ab3304ad38
    # Associate the AWS WAF web ACL with the ALB to protect against common web exploits and bots.
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:801100257021:regional/webacl/redemption/702b6da4-4638-4bc7-9f7e-68fcd07b737f
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
spec:
  ingressClassName: alb
  rules:
    - host: redemption.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redemption-api
                port:
                  number: 80
