# Application workload identity (no AWS perms needed at runtime).
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redemption-api
  namespace: redemption
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redemption-secretstore
  namespace: redemption
  annotations:
    # Replace with terraform output: app_secrets_irsa_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::801100257021:role/redemption-dev-external-secrets
